config/routes.rb
EaBA::Application.routes.draw do
  resources :orders
  resources :client_users
  resources :client_user_sessions, only: [:new, :create, :destroy]
  resources :restaurant_user_sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/client_user_signup', to: 'ClientUsers#new'
  match '/restaurant_user_signup', to: 'RestaurantUsers#new'
  match '/client_user_login', to: 'ClientUserSessions#new'
  match '/client_user_logout', to: 'ClientUserSessions#destroy', via: :delete
  match '/restaurant_user_login', to: 'RestaurantUserSessions#new'
  match '/restaurant_user_login', to: 'RestaurantUserSessions#destroy', via: :delete
  match '/restaurant_user_logout', to: 'RestaurantUserSessions#destroy', via: :delete

end

app/models/administrator.rb
# == Schema Information
#
# Table name: administrators
#
#  id           :integer          not null, primary key
#  account_name :string(255)
#  real_name    :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Administrator < ActiveRecord::Base
  attr_accessible :account_name, :real_name
end

app/models/client_to_restaurant_review.rb
# == Schema Information
#
# Table name: client_to_restaurant_reviews
#
#  id            :integer          not null, primary key
#  client_id     :integer
#  restaurant_id :integer
#  review        :string(255)
#  score         :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class ClientToRestaurantReview < ActiveRecord::Base
  attr_accessible :client_id, :restaurant_id, :review, :score
end

app/models/client_user.rb
# == Schema Information
#
# Table name: client_users
#
#  id           :integer          not null, primary key
#  gender       :string(255)
#  birthdate    :date
#  zipcode      :string(255)
#  address      :string(255)
#  phone        :string(255)
#  account_name :string(255)
#  real_name    :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class ClientUser < ActiveRecord::Base
  attr_accessible :account_name, :address, :birthdate, :gender, :phone, :real_name, :zipcode, :password, :password_confirmation

  has_secure_password

  before_save { |client_user| client_user.account_name.downcase! }
  before_save :create_remember_token

  GENDERS = [:male, :female]

  validates :account_name, presence: true, length: { minimum:4 }, 
	  uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum:4 }
  validates :password, presence: true
  private
  def create_remember_token
	  self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id                 :integer          not null, primary key
#  client_user_id     :integer
#  restaurant_user_id :integer
#  content            :string(255)
#  address            :string(255)
#  zipcode            :string(255)
#  phone              :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Order < ActiveRecord::Base
  attr_accessible :address, :client_user_id, :content, :phone, :restaurant_user_id, :zipcode
end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id            :integer          not null, primary key
#  camis         :string(255)
#  dba           :string(255)
#  boro          :string(255)
#  building      :string(255)
#  street        :string(255)
#  zipcode       :string(255)
#  phone         :string(255)
#  cuisine       :string(255)
#  insp_date     :string(255)
#  action        :string(255)
#  violcode      :string(255)
#  score         :string(255)
#  current_grade :string(255)
#  grade_date    :string(255)
#  record_date   :string(255)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Restaurant < ActiveRecord::Base
  attr_accessible :action, :boro, :building, :camis, :cuisine, :current_grade, :dba, :grade_date, :insp_date, :phone, :record_date, :score, :street, :violcode, :zipcode
end

app/models/restaurant_to_client_review.rb
# == Schema Information
#
# Table name: restaurant_to_client_reviews
#
#  id            :integer          not null, primary key
#  client_id     :integer
#  restaurant_id :integer
#  review        :string(255)
#  score         :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class RestaurantToClientReview < ActiveRecord::Base
  attr_accessible :client_id, :restaurant_id, :review, :score
end

app/models/restaurant_user.rb
# == Schema Information
#
# Table name: restaurant_users
#
#  id            :integer          not null, primary key
#  license_no    :string(255)
#  phone         :string(255)
#  restaurant_id :integer
#  account_name  :string(255)
#  real_name     :string(255)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class RestaurantUser < ActiveRecord::Base
  attr_accessible :account_name, :license_no, :phone, :real_name, :restaurant_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include ClientUserSessionsHelper
  include RestaurantUserSessionsHelper
end

app/controllers/client_users_controller.rb
class ClientUsersController < ApplicationController
	def new
		@client_user = ClientUser.new
	end

	def create
		@client_user = ClientUser.new(params[:client_user])
		if @client_user.save
			flash[:success] = "You have successfully created your account!"
			client_user_login @client_user
			redirect_to @client_user 
		else
			render 'new'
		end
	end

	def show
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def new
		@order = Order.new
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "EaBA"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/client_user_sessions_helper.rb
module ClientUserSessionsHelper
  def client_user_login(user)
	cookies.permanent[:remember_token] = user.remember_token
	self.current_client_user = user
  end

  def client_user_loged_in?
    !current_client_user.nil?
  end

  def current_client_user=(user)
    @current_client_user = user
  end

  def current_client_user
    @current_client_user ||= ClientUser.find_by_remember_token(cookies[:remember_token])
  end

  def current_client_user?(user)
    user == current_client_user
  end

  def client_user_logout
    current_client_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/client_users_helper.rb
module ClientUsersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/restaurant_users_helper.rb
module RestaurantUsersHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">EaBA</a>
	By ECoders
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   "#" %></li>
      <li><%= link_to "Contact", "#" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
<div class="navbar-inner">
	<div class="container">
		<%= link_to "EaBA", root_path, id: "logo" %>
		<nav>
		<ul class="nav pull-right">
			<% if client_user_loged_in? %>
				<li><%= link_to "Profile", "#" %></li>
				<li><%= link_to "Preference", "#" %></li>
				<li><%= link_to "Orders", "#" %></li>
				<li><%= link_to "Reviews", "#" %></li>
				<li>
					<%= link_to "Logout", client_user_logout_path, method: "delete" %>
				</li>
			<% elsif restaurant_user_loged_in? %>
				<li><%= link_to "Restaurant", "#" %></li>
				<li><%= link_to "Orders", "#" %></li>
				<li><%= link_to "Reviews", "#" %></li>
				<li>
					<%= link_to "Logout", restaurant_user_logout_path, method: "delete" %>
				</li>
			<% else %>
				<li><%= link_to "Client User", client_user_login_path %></li>
				<li><%= link_to "Restaurant User", restaurant_user_login_path %></li>
			<% end %>
		</ul>
		</nav>
	</div>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    "application", media: "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>    
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>